config/routes.rb
Rails.application.routes.draw do
  get '/main' => 'main#new'
  get 'contact' => 'main#contact'
  root 'main#new'

  get 'search/ajax'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  get '/signup' => 'user#new'
  post '/user' => 'user#create'


  resources :search
  resources :all_recipe
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :specifications
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  has_many :specifications
  has_attached_file :avatar, styles: { medium: '300x300>' }, default_url: 'app/assets/images/missing.png'
end

app/models/specification.rb
class Specification < ApplicationRecord
  belongs_to :recipe
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name,
            presence: true,
            uniqueness: true,
            format: { with: /\A[a-zA-Z0-9._%+-]+\z/ }
  validates :email,
            presence: true,
            uniqueness: true,
            email_format: { message: 'is not looking good' }
  validates :password_digest,
            presence: true,
            confirmation: true
end

app/controllers/all_recipe_controller.rb
# frozen_string_literal: true
class AllRecipeController < ApplicationController
  before_action :authorize
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    @specifications = Specification.where(:recipe_id => @recipe.id)
    @product = []
    @specifications.each { |s| @product.push(Product.find(s.product_id)) }
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale

  def set_locale
    session[:locale] = params[:locale] if params[:locale]
    I18n.locale = session[:locale] || I18n.default_locale
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to '/login' unless current_user
  end

  def deny_access_to_authorized
    redirect_to '/main' if current_user
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  before_action :authorize
  def new; end

  def contact; end
end

app/controllers/search_controller.rb
# frozen_string_literal: true

class SearchController < ApplicationController
  before_action :authorize
  def index; end

  def ajax
    @product1 = Product.find(params[:id_1])
    @product2 = Product.find(params[:id_2])
    ids = Recipe.joins(:specifications).where(specifications: { product_id: @product1.id })
                .or(Recipe.joins(:specifications).where(specifications: { product_id: @product2.id }))
                .group('recipes.id')
                .having('count(specifications.id) = 2')
                .pluck(:id)
    @result = Recipe.find(ids)
    respond_to { |format| format.json { render json: { solution: @result } } }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :deny_access_to_authorized, only: %i[new create]
  def new; end

  def create
    user = User.find_by_name(params[:username])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/main'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def new; end

  def create
    user = User.new(user_params)
    if user.save
      session[:user_id] = user.id
      redirect_to '/main'
    else
      flash[:alert] = 'invalid data'
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/all_recipe_helper.rb
module AllRecipeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/all_recipe/index.html.haml
%main{:role => "main"}
  / Main jumbotron for a primary marketing message or call to action
  .container
    %h1.display-3
      = t('all_recipe.our_recipe')
    %p
      = t('all_recipe.text')
    .row
      .col-md-12
        %table.table
          %tr
            %th
              = t('search.title')
            %th
              = t('search.time')
            %th
          - @recipes.each do |recipe|
            %tr
              %td= recipe.title
              %td= recipe.time_work
              %td= link_to t('all_recipe.more'), all_recipe_path(recipe)
      %hr/

app/views/all_recipe/show.html.haml
%main{:role => "main"}
  .row
    .container
      %h1.display-3
        %strong
          = t('all_recipe.show.title')
        = @recipe.title
    .container
      .row
        .col-md-3
          %table.table
            %tr
              %th
                = t('all_recipe.show.product')
              %th
                = t('all_recipe.show.count')
            - @product.each_with_index do |prod, i|
              %tr
                %td
                  = prod.title
                %td
                  = @specifications[i].count
        .col-md-9
          %h2
            = t('all_recipe.show.todo')
          %p= @recipe.text
      %hr/

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ExamWork
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1, shrink-to-fit=no", :name => "viewport"}/
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body#page-top
    .header
      %nav.navbar.navbar-expand-md.fixed-top.navbar-dark.bg-dark
        %h1.navbar-brand Food4u
        - if current_user
          %span.nav-link
            = t('navbar.user')
            #{current_user.name}
          %a.btn.btn-outline-secondary{:href => "/logout"}
            %span
              = t('navbar.singout')
        - else
          %a.btn.btn-outline-secondary{:href => "/login"}
            %span
              = t('navbar.singin')
          %a.btn.btn-outline-secondary{:href => "/signup"}
            %span
              = t('navbar.singup')
        %button.navbar-toggler.p-0.border-0{"data-toggle" => "offcanvas", :type => "button"}
          %span.navbar-toggler-icon
        .navbar-collapse.offcanvas-collapse
          %ul.navbar-nav.mr-auto
            %li.nav-item.active
              %a{:href => "/#main"}
                %span.nav-link
                  = t('navbar.item.main')
            %li.nav-item
              %a{:href => "/search"}
                %span.nav-link
                  = t('navbar.item.search')
            %li.nav-item
              %a{:href => "/all_recipe"}
                %span.nav-link
                  = t('navbar.item.all_recipe')
            %li.nav-item
              %a{:href => "https://www.delivery-club.ru/entities/food", :target => "_blank"}
                %span.nav-link
                  = t('navbar.item.lazy')
            %li.nav-item
              %a#contact-link{:href => "/contact"}
                %span.nav-link
                  = t('navbar.item.contact')
            %li.nav-item.dropdown
              %a#dropdown01.nav-link.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown"}
                = t('navbar.item.lang')
              .dropdown-menu{"aria-labelledby" => "dropdown01"}
                %a.dropdown-item{:href => "?locale=en"} English
                %a.dropdown-item{:href => "?locale=ru"} Русский
    .container
      = yield
    %footer.footer
      .container
        %span.text-muted © Food4u. Designed by I.Kravtsov
        %a{:href => "mailto:vanekkravtsov@mail.ru"} vanekkravtsov@mail.ru

app/views/main/contact.html.haml
.container.marketing
  .row
    .col-lg-4
      %img.rounded-circle{:alt => "Generic placeholder image", :height => "140", :src => "https://i.pinimg.com/564x/d1/9e/b9/d19eb960e5ea43dcfcfb50b80b80c0ab.jpg", :width => "140"}/
      %h2 Instagram
      %p
        %a.btn.btn-secondary{:href => "https://www.instagram.com/_i.kravtsov_/?hl=ru", :role => "button"} @_i.kravtsov_
    .col-lg-4
      %img.rounded-circle{:alt => "Generic placeholder image", :height => "140", :src => "https://pbs.twimg.com/profile_images/1157035760085684224/iuxTnT5g_400x400.jpg", :width => "140"}/
      %h2 Github
      %p
        %a.btn.btn-secondary{:href => "https://github.com/ololo534", :role => "button"} github.com/ololo534
    .col-lg-4
      %img.rounded-circle{:alt => "Generic placeholder image", :height => "140", :src => "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/VK.com-logo.svg/192px-VK.com-logo.svg.png", :width => "140"}/
      %h2 Vk
      %p
        %a.btn.btn-secondary{:href => "https://vk.com/vanekkravtsov", :role => "button"} vk.com/vanekkravtsov

app/views/main/new.html.haml
%body
  .cover-container.d-flex.h-100.p-3.mx-auto.flex-column
    %header.masthead.mb-auto
    %main.inner.cover{:role => "main"}
      %h1.cover-heading Food4u
      %p.lead
        = t('main.main_text')
      %p.lead
        %a.btn.btn-lg.btn-secondary{:href => "/search"}
          = t('navbar.item.search')
    .shadow

app/views/search/index.html.haml
%main{:role => "main"}
  .container
    %h1.display-3
      = t('search.select_text')
    = form_with id: 'form', method: :get, url: search_ajax_path do |form|
      - product_array = Product.all.map {|prod| [prod.title, prod.id]}
      = select_tag(:id_1, options_for_select(product_array), :class => 'browser-default custom-select')
      %hr/
      = select_tag(:id_2, options_for_select(product_array), :class => 'browser-default custom-select')
      %hr/
      = form.submit  t('search.search'), :class => 'btn btn-lg btn-secondary'
      %hr/
  .container
    .row
      .col-md-12
        %table#table.table{:style => "display:none"}
          %tr
            %th
              = t('search.title')
            %th
              = t('search.time')
            %th
        #error.alert.alert-danger{:style => "display:none"}
          %strong
            = t('search.error')

app/views/user/new.html.haml
= form_for :user, url: '/user' do |f|
  %h1
    = t('navbar.singup')
  %label{:for => "user_name"}
  %input#user_name{:name => "user[name]", :placeholder => t('username'), :type => "text"}/
  %label{:for => "user_email"}
  %input#user_email{:name => "user[email]", :placeholder => "e-mail", :type => "text"}/
  %label{:for => "user_password"}
  %input#user_password{:name => "user[password]", :placeholder => t('password'), :type => "password"}/
  %label{:for => "user_password_confirmation"}
  %input#user_password_confirmation{:name => "user[password_confirmation]", :placeholder => t('password_conf'), :type => "password"}/
  %input.btn.btn-primary{"data-disable-with" => t('sing_attempt'), :name => "commit", :type => "submit", :value => t('sing_up')}/
  %br/
  %br/
  %a{:href => "/login"}
    = t('back')